### ISSUE TITLE
sapien version issue

### ISSUE THREAD

**Issue by xsaxasni** [sxy7147/DualAfford#1]
Hello, the 0.8.0 version cannot be downloaded now. 
I downloaded the 0.10.1 version and encountered 
ImportError: cannot import name 'ArticulationJointType' from 'sapien.core' (/home/xxx/anaconda3/envs/dualafford/lib/python3.8/site-packages/sapien/core/__init__.py). 
How can I solve this problem? 
Looking forward to your reply.
Thanks.

**Comment by FaizalKarim280280** [comment]
Hello, is this issue solved? I am facing the same problem.

**Comment by sxy7147** [comment]
> Hello, is this issue solved? I am facing the same problem.


Hi, I have updated the repository and added the file `sapien-0.8.0.dev0-cp36-cp36m-manylinux2014_x86_64.whl` to the `./code` directory.
